version: '3.4'

services:
  isitweeka:
    image: isitweeka
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      NODE_ENV: production
      IIWA_REDIS_URL: redis://redis_comms:6379
    ports:
      - 4000:4000
    links:
      - redis
    
  service-kech:
    image: isitweeka-service-kech
    build:
      context: .
      dockerfile: ./packages/@isitweeka/service-kech/Dockerfile
    environment:
      NODE_ENV: production
      IIWA_REDIS_URL: redis://redis_comms:6379
    links:
      - redis
  
  service-eventbrite:
    image: isitweeka-service-eventbrite
    build:
      context: .
      dockerfile: ./packages/@isitweeka/service-eventbrite/Dockerfile
    environment:
      NODE_ENV: production
      IIWA_REDIS_URL: redis://redis_comms:6379
      IIWA_EVENTBRITE_ORG_ID: ${IIWA_EVENTBRITE_ORG_ID}
      IIWA_EVENTBRITE_EVENT_ID: ${IIWA_EVENTBRITE_EVENT_ID}
      IIWA_EVENTBRITE_ACCESS_TOKEN: ${IIWA_EVENTBRITE_ACCESS_TOKEN}
    links:
      - redis
    
  redis:
    image: redis:alpine
    container_name: redis_comms
    ports:
      - 6379:6379
