version: '3.4'

services:
  isitweeka:
    image: isitweeka
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      NODE_ENV: production
      IIWA_REDIS_URL: redis://redis_comms:6390
    ports:
      - 4000:4000
    links:
      - redis
  service-kech:
    image: isitweeka-service-kech
    build:
      context: .
      dockerfile: ./packages/@isitweeka/service-kech/Dockerfile
    environment:
      NODE_ENV: production
      IIWA_REDIS_URL: redis://redis_comms:6390
    links:
      - redis
  redis:
    image: redis:alpine
    container_name: redis_comms
    ports:
      - 6390:6379
