# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Website Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Prepare repo/ as a git repo
      run: |
        mkdir repo
        cd repo
        echo Cloning repo...
        git clone https://github.com/$GITHUB_REPOSITORY --branch gh-pages ./
        echo Deleteing dirs...
        find . ! -wholename './.git/*' ! -wholename './.git' ! -wholename '.' -type d -exec rm -rfv {} +
        echo Deleteing files...
        find . ! -wholename './.git/*' -type f -exec echo {} +
        echo Staging...
        git add .
    - run: yarn
      working-directory: ./frontend
    - run: yarn run build
      env:
        CI: "false"
      working-directory: ./frontend
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Website Build
        # A file, directory or wildcard pattern that describes what to upload
        path: build/
      working-directory: ./frontend
    - name: Copy build files
      run: cp -va ./build/. ../repo/
      working-directory: ./frontend
    - name: Commit changes
      if: ${{ contains(github.ref, 'main') }} # Only run if this repo is main and the development branch
      run: |
        cd repo
        echo Setting git settings
        git config user.email "kishansambhi@hotmail.co.uk"
        git config user.name "Kishan Build Agent"
        git add .
        git commit -m "Build push for commit $GITHUB_SHA run ID $GITHUB_RUN_ID"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      if: ${{ contains(github.ref, 'main') }} # Only run if this repo is main and the development branch
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        # repository: # optional, default is 
        # Destination branch to push changes
        branch: gh-pages
        # Determines if force push is used
        force: true
        # Directory to change to before pushing.
        directory: repo